FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 \
    VIGIE_HOST=0.0.0.0 VIGIE_PORT=8765 \
    VIGIE_DATA_DIR=/data VIGIE_DB_FILENAME=vigie-staging.sqlite3 \
    VIGIE_COOKIE_SECURE=1
WORKDIR /app
COPY . /app
EXPOSE 8765
CMD ["python", "server.py"]
